# Generated by Django 5.1.6 on 2026-07-22 06:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ornament',
            name='uniq_ornament_per_shop',
        ),
        migrations.AddConstraint(
            model_name='ornament',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('shop'), name='uniq_ornament_name_ci_per_shop'),
        ),
    ]
