# Generated by Django 5.1.6 on 2026-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_ornament_uniq_ornament_per_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkarigarprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='karigarprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
