# Generated by Django 5.1.6 on 2026-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='date_format',
            field=models.CharField(choices=[('DMY_TEXT', '27 Magh 2080 (day month year)'), ('YMD', '2080-10-27 (year-month-day)'), ('DMY', '27/10/2080 (day/month/year)'), ('MDY', '10/27/2080 (month/day/year)')], default='DMY_TEXT', max_length=10),
        ),
    ]
