# Generated by Django 5.1.6 on 2026-07-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_default_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('plan', models.CharField(blank=True, help_text="Optional label, e.g. 'Monthly', 'Annual'.", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop__name'],
            },
        ),
    ]
