# Generated by Django 5.1.6 on 2026-07-22 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appsetting_date_format'),
        ('backups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfig',
            name='recipient_emails',
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='primary_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='secondary_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='frequency',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='off', max_length=10),
        ),
        migrations.CreateModel(
            name='RestoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_filename', models.CharField(max_length=255)),
                ('safety_backup_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_audits', to='accounts.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BackupLog',
        ),
    ]
